### ISSUE TITLE
l10n directory not writeable

### ISSUE THREAD

**Issue by geldmacher** [platformsh/platformsh-example-typo3#11]
It is impossible to import translations because typo3conf/l10n/ is not writeable.

**Comment by JGrubb** [comment]
Hi, try adding that directory to the `mounts` section of your `.platform.app.yaml` file.  Like so,

```yaml
mounts:
  "web/typo3temp/assets": "shared:files/tmp-assets"
  "web/typo3temp/var": "shared:files/tmp-var"
  "web/uploads": "shared:files/uploads"
  "web/fileadmin": "shared:files/fileadmin"
  "web/typo3conf/writeable": "shared:files/config"
  "web/typo3conf/l10n": "shared:files/l10n"
```
